name: CI/CD Deploy to EC2 (Nginx)

on:
  push:
    branches:
      - main   # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Install Nginx and Setup Web Root Directory
        run: |
          # Update and install Nginx
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo apt update
            sudo apt install -y nginx
            sudo mkdir -p /var/www/html
            sudo chown www-data:www-data /var/www/html
          EOF

      - name: Deploy index.html to EC2
        run: |
          # Copy index.html to EC2
          scp -o StrictHostKeyChecking=no index.html ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/index.html
          
          # Move the file into the web root and restart Nginx
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo mv /tmp/index.html /var/www/html/index.html
            sudo chown www-data:www-data /var/www/html/index.html
            sudo systemctl restart nginx
          EOF
