name: Deploy Static Website to EC2

on:
  push:
    branches:
      - main   # Deploy only when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Copy HTML file to EC2
      - name: Deploy index.html to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Copy index.html to EC2's web root
          scp -o StrictHostKeyChecking=no -i private_key.pem index.html $EC2_USER@$EC2_HOST:/var/www/html/index.html

      # Step 3: Restart web server (optional)
      - name: Restart Web Server
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "
            if command -v nginx > /dev/null; then
              sudo systemctl restart nginx
            elif command -v apache2 > /dev/null; then
              sudo systemctl restart apache2
            fi
          "
