name: Deploy Static Website to EC2

on:
  push:
    branches: [ "main" ]   # Deploy only when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy website to EC2 using rsync
        run: |
          rsync -avz --delete \
            --exclude ".git*" \
            --exclude ".github" \
            -e "ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=yes" \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.DEPLOY_PATH }}

      - name: Reload Nginx (optional)
        run: |
          ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=yes \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "sudo systemctl reload nginx || true"
