name: Deploy Static Site to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=yes" \
            ./ \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/

          ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=yes ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Update system
            if [ -x "$(command -v apt)" ]; then
              sudo apt update -y
              sudo apt install -y nginx
            elif [ -x "$(command -v yum)" ]; then
              sudo yum update -y
              sudo amazon-linux-extras enable nginx1 || true
              sudo yum install -y nginx
            fi

            # Enable and start nginx
            sudo systemctl enable nginx
            sudo systemctl start nginx

            # Create a clean nginx config
            SITE_NAME=static-site
            CONF_FILE="/etc/nginx/sites-available/$SITE_NAME"

            # For Ubuntu/Debian (sites-available/sites-enabled structure)
            if [ -d "/etc/nginx/sites-available" ]; then
              sudo tee $CONF_FILE > /dev/null <<EOL
server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL
              sudo ln -sf $CONF_FILE /etc/nginx/sites-enabled/
              sudo rm -f /etc/nginx/sites-enabled/default
            else
              # For Amazon Linux / CentOS (default config at nginx.conf)
              sudo tee /etc/nginx/conf.d/$SITE_NAME.conf > /dev/null <<EOL
server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL
            fi

            # Test and reload nginx
            sudo nginx -t
            sudo systemctl reload nginx
          EOF

