name: Deploy Static Site to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=yes" \
            ./ \
            "${{ secrets.EC2_USER }}"@"${{ secrets.EC2_HOST }}":/var/www/html/

          ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=yes "${{ secrets.EC2_USER }}"@"${{ secrets.EC2_HOST }}" bash <<'EOF'
            if [ -x "$(command -v apt)" ]; then
              sudo apt update -y
              sudo apt install -y nginx
            elif [ -x "$(command -v yum)" ]; then
              sudo yum update -y
              sudo amazon-linux-extras enable nginx1 || true
              sudo yum install -y nginx
            fi

            sudo tee /etc/nginx/conf.d/default.conf > /dev/null <<'NGINX_CONF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }
}
NGINX_CONF

            sudo nginx -t
            sudo systemctl enable nginx
            sudo systemctl restart nginx
EOF
